frontend:
  image:
    repository: naver-fashion-ad-dashboard-frontend
    tag: latest
  replicas: 1
  port: 80

backend:
  image:
    repository: naver-fashion-ad-dashboard-backend
    tag: latest
  replicas: 1
  port: 8000
